zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      url: http://localhost:8073
    #      serviceId: HELLO-SERVER
    hello-client:
      path: /client/**
      serviceId: hello-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9070/eureka/
    registerWithEureka: true
  instance:
    hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuul-service
